WAAdmin disableDevelopmentTools.
EvolvingEaterWebView
	stopServer;
	unregisterFromApplications.
Smalltalk garbageCollect.

EvolvingEaterWebView 
	startServer;
	registerApplication.
"--------------------------------------------"
WAAdmin disableDevelopmentTools.
WindExperimentWebView
	stopServer;
	unregisterFromApplications.
Smalltalk garbageCollect.

WindExperimentWebView 
	startServer;
	registerApplication.
"--------------------------------------------"
WAAdmin disableDevelopmentTools.
WindExperimentWebView
	stopServer;
	unregisterFromApplications.
EvolvingEaterWebView 
	unregisterFromApplications.
Smalltalk garbageCollect.

WindExperimentWebView 
	startServer;
	registerApplication.
EvolvingEaterWebView
	registerApplication.