experimenting - mines
dumpSimpleRMaxMinesExperimentFiles

	"	self dumpSimpleRMaxMinesExperimentFilesBuildingWorldsOfSize:5 planting: 5 discountingAt: 0.9999.
	self dumpSimpleRMaxMinesExperimentFilesBuildingWorldsOfSize:10 planting: 5 discountingAt: 0.9999.
	self dumpSimpleRMaxMinesExperimentFilesBuildingWorldsOfSize:10 planting: 40 discountingAt: 0.9999."

	self
		dumpSimpleRMaxMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 40
		discountingAt: 0.95