experimenting - multi
dumpSimpleRMaxMOMinesExperimentFiles

	self
		dumpSimpleRMaxMOMinesExperimentFilesBuildingWorldsOfSize: 5
		planting: 1
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 1
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.95