experimenting - wind
dumpExperienceReplayWindExperimentFiles

	self
		dumpExperienceReplayWindExperimentFilesBuildingWorldsOfSize: 5
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpExperienceReplayWindExperimentFilesBuildingWorldsOfSize: 10
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpExperienceReplayWindExperimentFilesBuildingWorldsOfSize: 10
		discountingAt: 0.9999
		learningAt: 0.3
		exploringWithProbability: 0.1.
	self
		dumpExperienceReplayWindExperimentFilesBuildingWorldsOfSize: 10
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.4.
	self
		dumpExperienceReplayWindExperimentFilesBuildingWorldsOfSize: 10
		discountingAt: 0.95
		learningAt: 0.1
		exploringWithProbability: 0.1