experimenting - mines
dumpQLearnMinesExperimentFiles

	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 5
		planting: 5
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 5
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 40
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 40
		discountingAt: 0.9999
		learningAt: 0.3
		exploringWithProbability: 0.1.
	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 40
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.4.
	self
		dumpQLearnMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 40
		discountingAt: 0.95
		learningAt: 0.1
		exploringWithProbability: 0.1