experimenting - multi
dumpQLearnMOMinesExperimentFiles

	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 5
		planting: 1
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 1
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.1.
	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.9999
		learningAt: 0.3
		exploringWithProbability: 0.1.
	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.9999
		learningAt: 0.1
		exploringWithProbability: 0.4.
	self
		dumpQLearnMOMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.95
		learningAt: 0.1
		exploringWithProbability: 0.1