experimenting - multi
dumpSimpleRMaxMultiObjectiveMinesExperimentFiles

	self
		dumpSimpleRMaxMultiObjectiveMinesExperimentFilesBuildingWorldsOfSize: 5
		planting: 1
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMultiObjectiveMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 1
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMultiObjectiveMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.9999.
	self
		dumpSimpleRMaxMultiObjectiveMinesExperimentFilesBuildingWorldsOfSize: 10
		planting: 30
		discountingAt: 0.95