SystemOrganization addCategory: #'NeuralNetworkEvolution-Model'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-AssignmentModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-EnvironmentModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-ExperimentModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-GeometryModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-NeuralNetworkModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-OrganismModel'!
SystemOrganization addCategory: 'NeuralNetworkEvolution-Model-SelectionModel'!
