defaults
defaultSurvivalPercentage

	"...in our case we consider that only 40% of the individuals will survive in each generation..."
	"Final value (40%) has been selected from initial estimations presented in figure 5.
	Gimeno, Ricardo and Nave, Juan Miguel,Genetic Algorithm Estimation of Interest Rate Term Structure(December 11, 2006). Banco de Espana Research Paper No. WP-0634. Available at SSRN: http://ssrn.com/abstract=950982.
	-mtabacman"

	^40/100